version: '3.7'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: lessgo123
      MYSQL_DATABASE: db_name
      MYSQL_USER: user
      MYSQL_PASSWORD: userpsw
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: lessgo123
    ports:
      - "8080:80"

volumes:
  db_data:
