version: '3.9'

services:
  node:
    build: ./app
    ports:
      - "8080:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: lessgo123
      MYSQL_DATABASE: dbpsw
      MYSQL_USER: user
      MYSQL_PASSWORD: userpsw
    ports:
      - "8080:80"  
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
